CompanyEquip/Controllers/EquipmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Entities;
using Library.Converter;
using Models;
using PagedList;
using Services;

namespace CompanyEquip.Controllers
{
    public class EquipmentsController : Controller
    {
        public IEquipmentService equipmentService;

        public EquipmentsController(IEquipmentService equipmentService)
        {
            this.equipmentService = equipmentService;
        }

        // Index: Equipments
        #region Index
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.SerialNumber = sortOrder == "Date" ? "date_desc" : "serialNumber_desc" ;

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var equipments = equipmentService.GetWithPagination(sortOrder, searchString);

            int pageSize = 20;
            int pageNumber = (page ?? 1);
            return View(equipments.ToPagedList(pageNumber, pageSize));
        }
        #endregion Index

        // Details: Equipments
        #region Details
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            int ID = id ?? 0;
            var equipment = equipmentService.GetById(ID);
            if (equipment == null)
            {
                return HttpNotFound();
            }
            var equipmentModel = new EquipmentModel();
            equipmentModel.Id = equipment.Id;
            equipmentModel.SerialNumber = equipment.SerialNumber;
            equipmentModel.Name = equipment.Name;
            equipmentModel.NextControlDate = DateConverter.DatetTimeToString(equipment.NextControlDate);
            equipmentModel.Image = equipment.Image;
            return View(equipmentModel);
        }
        #endregion Details

        // Create: Equipments
        #region Create
        public ActionResult Create()
        {
            EquipmentModel equipmentModel = new EquipmentModel();
            return View(equipmentModel);
        }

        [HttpPost]
        public ActionResult Create(EquipmentModel equipmentModel, HttpPostedFileBase ImageEquip)
        {
            var equipment = new Equipment();
            equipment.Name = equipmentModel.Name;
            equipment.SerialNumber = equipmentModel.SerialNumber;
            equipment.NextControlDate = DateConverter.StringToDateTime(equipmentModel.NextControlDate);
            if (ImageEquip != null && ImageEquip.ContentLength > 0)
            {
                equipment.Image = new byte[ImageEquip.ContentLength]; // ImageEquip to store image in binary formate  
                ImageEquip.InputStream.Read(equipment.Image, 0, ImageEquip.ContentLength);
            }
            try
            {
                if (ModelState.IsValid)
                {
                    var inserted = equipmentService.Insert(equipment);
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return View(equipmentModel);
        }
        #endregion

        // Edit: Equipments
        #region Edit      
        //[ValidateAntiForgeryToken]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            int ID = id ?? 0;
            var equipment = equipmentService.GetById(ID);
            if (equipment == null)
            {
                return HttpNotFound();
            }
            var equipmentModel = new EquipmentModel();
            equipmentModel.Id = equipment.Id;
            equipmentModel.SerialNumber = equipment.SerialNumber;
            equipmentModel.Name = equipment.Name;
            equipmentModel.NextControlDate = DateConverter.DatetTimeToString(equipment.NextControlDate);
            equipmentModel.Image = equipment.Image;
            return View(equipmentModel);
        }

        [HttpPost]
        public ActionResult Edit(EquipmentModel equipmentModel, HttpPostedFileBase ImageEquip)
        {
            if (ModelState.IsValid)
            {
                var oldEquipment = equipmentService.GetById(equipmentModel.Id);
                var equipment = new Equipment();
                equipment.Name = equipmentModel.Name;
                equipment.SerialNumber = equipmentModel.SerialNumber;
                equipment.NextControlDate = DateConverter.StringToDateTime(equipmentModel.NextControlDate);
                if (ImageEquip != null && ImageEquip.ContentLength > 0)
                {
                    equipment.Image = new byte[ImageEquip.ContentLength]; // ImageEquip to store image in binary formate  
                    ImageEquip.InputStream.Read(equipment.Image, 0, ImageEquip.ContentLength);
                }

                /* Other Method : Insert image into folder and insert image path into database and display image in 
                 * view from image folder based on path given(stored) in database. */
                //if (ImageEquip == null)
                //{
                //    string ImageName = System.IO.Path.GetFileName(ImageEquip.FileName); //file2 to store path and url  
                //    string physicalPath = Server.MapPath("~/img/" + ImageName);
                //    // save image in folder  
                //    ImageEquip.SaveAs(physicalPath);
                //    equip.PathPhoto = "img/" + ImageName;
                //}

                var updated = equipmentService.Update(oldEquipment, equipment);
                return RedirectToAction("Index");
            }

            return View(equipmentModel);
        }
        #endregion Edit

        // Delete: Equipments
        #region Delete
        public ActionResult Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Delete failed. Try again, and if the problem persists see your system administrator.";
            }
            var ID = id ?? 0;
            var equipment = equipmentService.GetById(ID);
            if (equipment == null)
            {
                return HttpNotFound();
            }
            return View(equipment);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                var equipment = equipmentService.GetById(id);
                var deleted = equipmentService.Delete(equipment);
            }
            catch (DataException/* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }
            return RedirectToAction("Index");
        }
        #endregion Delete
    }
}

CompanyEquip/Views/Equipments/Create.cshtml
@model Models.EquipmentModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Equipments", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>EquipmentModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.SerialNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SerialNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SerialNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NextControlDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NextControlDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NextControlDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBox("ImageEquip", null, new { @class = "form-control", type = "file" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CompanyEquip/Views/Equipments/Delete.cshtml
<h2>Delete</h2>
<p class="error">@ViewBag.ErrorMessage</p>
<h3>Are you sure you want to delete this?</h3>
@using (Html.BeginForm("Delete", "Equipments", FormMethod.Post))
{

}

CompanyEquip/Views/Equipments/Details.cshtml
@model Models.EquipmentModel

@{
    ViewBag.Title = "Details";
}

@{
    var imgSrc = "";
    if (Model.Image != null)
    {
        var base64 = Convert.ToBase64String(Model.Image);
        imgSrc = String.Format("data:image/gif;base64,{0}", base64);
    }
    else
    {
        imgSrc = null;
    }
}

<h2>Details</h2>

<div>
    <h4>EquipmentModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SerialNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SerialNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NextControlDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NextControlDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            <img src="@imgSrc" style="max-width:100px; max-height:100px" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CompanyEquip/Views/Equipments/Edit.cshtml
@model Models.EquipmentModel

@{
    ViewBag.Title = "Edit";
}

@{
    var imgSrc = "";
    if (Model.Image != null)
    {
        var base64 = Convert.ToBase64String(Model.Image);
        imgSrc = String.Format("data:image/gif;base64,{0}", base64);
    }
    else
    {
        imgSrc = null;
    }
}
    <h2>Edit</h2>

    @using (Html.BeginForm("Edit", "Equipments", new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>EquipmentModel</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.SerialNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SerialNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SerialNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NextControlDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NextControlDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NextControlDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.TextBox("ImageEquip", null, new { @class = "form-control", type = "file" })
                <img src="@imgSrc" style="max-width:100px; max-height:100px" />
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

CompanyEquip/Views/Equipments/Index.cshtml
@model PagedList.IPagedList<Models.EquipmentModel>
@using PagedList.Mvc;
@using Resources;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Equipments";
}

<h2>Equipments</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Index", "Equipments", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("SerialNumber", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Images", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Date", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        /* The images stored as Binary data will be fetched as BYTE Array and then, the BYTE Array will be converted to BASE 64 string and then displayed in View in ASP.NET MVC 5 */

        /* Other Method : Insert image into folder and insert image path into database and display image in view from image folder based on path given(stored) in database. */

        var imgSrc = "";
        if (item.Image != null)
        {
            var base64 = Convert.ToBase64String(item.Image);
            imgSrc = String.Format("data:image/gif;base64,{0}", base64);
        }
        else
        {
            imgSrc = null;
        }
        using (Html.BeginForm("Delete", "Equipments", new { id = item.Id }))
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SerialNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <img src="@imgSrc" style="max-width:100px; max-height:100px" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NextControlDate)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    <input type="submit" value="Delete" />
                    @*@Html.ActionLink("Delete", "Delete", new { id = item.Id },
                        new { onclick = "return confirm('Do you really want to delete the tag " + @item.Name + "?')" })*@
                </td>
            </tr>
        }
    }
</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

CompanyEquip/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>